#
# Realtek Semiconductor Corp.
#
#code by shanjian_fei 20150805
#

romfs:
	$(ROMFSINST) -p 755 exceptiontest.sh /bin/exceptiontest.sh
	$(ROMFSINST) -p 755 hotplug.sh /bin/hotplug.sh
	$(ROMFSINST) -p 755 write_stress /etc/sdtest/write_stress.job
	$(ROMFSINST) -p 755 write_full_device /etc/sdtest/write_full_device.job
	$(ROMFSINST) -p 755 write_verify /etc/sdtest/write_verify.job
	$(ROMFSINST) -p 755 write_runtime /etc/sdtest/write_runtime.job
	$(ROMFSINST) -p 755 write_size /etc/sdtest/write_size.job
	$(ROMFSINST) -p 755 burntest.sh /bin/burntest.sh
	$(ROMFSINST) -p 755 util.sh /bin/util.sh
