#ifndef _TESTUVC_H_
#define _TESTUVC_H_

#define EXU1_CMD_STS	0x0A
#define EXU1_DATA_INOUT 0X0B
#define MAX_RWFLASH_SIZE	8

#define VCMD_DBG	0x00
#define VCMD_ISP	0x01
#define VCMD_NVOL_RW	0x02
#define VCMD_IPCAM	0x03
#define VCMD_RST	0xFF
#define VCMD_CUSTOMER	0xF0

#define SCMD_DATA_VLD	0x80
#define SCMD_DIR_MSK	0x40
#define SCMD_DIR_IN	0x40
#define SCMD_DIR_OUT	0x00

#define VSCMD_IMEM_R			(0x01|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_XMEM_W			(0x02|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_XMEM_R			(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_CODE_R			(0x03|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_FLASH_E			(0x04)
#define VSCMD_FLASH_W			(0x05|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_FLASH_R			(0x05|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_FLASH_TAG			(0x06)
#define VSCMD_RST_2_UPDATEFW		(0x07)
#define VSCMD_RST_2_NEWCODE		(0x08)
#define VSCMD_RST_2_ROM			(0x09)
#define VSCMD_I2C_R			(0x0a|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_W			(0x0a|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_SFR_R			(0x0b|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SFR_W			(0x0b|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_PHY_R			(0x0c|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_PHY_W			(0x0c|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_DEV_STS_R			(0x0d|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SENSOR_I2CADDR_SET	(0x0e|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_DEV_QUALIFICATION_GET	(0x10|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_INIT_VD_FUNC_POINTER	(0x15)
#define VSCMD_INOUT_CTL_SIZE_SET	(0x16)
#define VSCMD_INOUT_CTL_SIZE_GET	(0x16|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_LEDMODE_SET		(0x17|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_LEDMODE_GET		(0x17|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_BAR_INFO_READ		(0x20|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_LED_TOGGLE		(0x22)
#define VSCMD_MIPI_APHY_I2C_R		(0X23|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_MIPI_APHY_I2C_W		(0X23|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_I2C_NORMAL_R		(0x2A|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_NORMAL_W		(0x2A|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_ISO_BULK_SWITCH		(0x2C|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_IQTABLE_PATCH_EN		(0x2E)
#define VSCMD_I2C_SUPER_R		(0x32|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_SUPER_W		(0x32|SCMD_DATA_VLD|SCMD_DIR_OUT)

#define CONTROL_INFO_SP_GET	        (1 << 0)
#define CONTROL_INFO_SP_SET	        (1 << 1)
#define CONTROL_INFO_DIS_BY_AUTO        (1 << 2)
#define CONTROL_INFO_SP_AUTOUPDATA	(1 << 3)
#define CONTROL_INFO_SP_ASYNC		(1 << 4)

#define VSCMD_SPI_SF_RID		(0x01|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SPI_SF_R			(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SPI_SF_W			(0x02|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_SPI_SF_RDSR		(0x03|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SPI_SF_WRSR		(0x03|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_SPI_SF_ERCHIP		(0X04)
#define VSCMD_SPI_SF_ERBLK		(0x05)
#define VSCMD_SPI_SF_FAST_R		(0x14|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SPI_SF_FAST_DUAL_OUT_R	(0x15|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_SPI_SF_FAST_DUAL_INOUT_R	(0x16|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_EEP_RID_BA		(0xa|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_EEP_R_BA		(0xb|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_EEP_W_BA		(0xb|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_I2C_EEP_ER_BA		(0xc)
#define VSCMD_I2C_EEP_RID_WA		(0x10|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_EEP_R_WA		(0X11|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_I2C_EEP_W_WA		(0X11|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_I2C_EEP_ER_WA		(0x12)
#define VSCMD_SPI_SF_WRITETAG		(0x13)

#define  VSCMD_GRY_MN_SET		(0x01|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define  VSCMD_GRY_MN_GET		(0x01|SCMD_DATA_VLD|SCMD_DIR_IN)
#define  VSCMD_NEGATIVE_SET		(0x02|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define  VSCMD_NEGATIVE_GET		(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_RAW_DAT_SET		(0X08|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_RAW_DAT_GET		(0x08|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_FRAME_STS_GET		(0x09|SCMD_DATA_VLD|SCMD_DIR_IN)
#define SNR_SPECIAL_EFFECT_SET		(0x0F|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define SNR_SPECIAL_EFFECT_GET		(0x0F|SCMD_DATA_VLD|SCMD_DIR_IN)
#define SNR_IMG_DIR_SET			(0x10|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define SNR_IMG_DIR_GET			(0x10|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_AE_WINDOW_SET		(0x14|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define ISP_AWB_GAIN_SET		(0x15|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define ISP_AWB_GAIN_GET		(0x15|SCMD_DATA_VLD|SCMD_DIR_IN)
#define AWB_GAIN_SUPPORT		(0x16|SCMD_DATA_VLD|SCMD_DIR_IN)

#define VSCMD_DBG_CMD			(0x01)
#define VSCMD_DBG_IN			(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_DBG_OUT			(0x02|SCMD_DATA_VLD|SCMD_DIR_OUT)

#define VSCMD_MTD_SENSITIVITY_SET	(0x15|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_MTD_SENSITIVITY_GET	(0x15|SCMD_DATA_VLD|SCMD_DIR_IN)
#define VSCMD_BACKGROUND_MTD_SET	(0x1D|SCMD_DATA_VLD|SCMD_DIR_OUT)
#define VSCMD_BACKGROUND_MTD_STOP	(0x1E)
#define VSCMD_CIRCUM_STATUS		(0x02|SCMD_DATA_VLD|SCMD_DIR_IN)

#define PREVIEW_LED_OFF			(0x0D)

#define DUMMY_BYTE (0XBB)

#define RTS1_CID_BASE			(V4L2_CID_USER_BASE | 0xf000)
#define V4L2_CID_ROLL_ABSOLUTE		(RTS1_CID_BASE+0)

typedef enum {
	VCMD_STS_CMD = 0,
	VCMD_STS_DATA_IN = 1,
	VCMD_STS_DATA_OUT = 2,
	VCMD_STS_ERR_DIR = 3,
	VCMD_STS_NOT_FINISH = 4,
	VCMD_STS_ERR_LEN = 5,
	VCMD_STS_UNKNOWN_SCMD = 6,
	VCMD_STS_ERR_OUTRANGE = 7,
	VCMD_STS_UNKNOWN_CMD = 8,
	VCMD_STS_HW_ERR = 9,
	VCMD_STS_RET_NO_ERR = 0XFE
} vcmdsts_t;

#define CLEAR(x) memset(&(x), 0, sizeof(x))

#define CTL_MIN_CT_EXPOSURE_TIME_ABSOLUTE (50)
#define CTL_MAX_CT_EXPOSURE_TIME_ABSOLUTE (10000)
#define CTL_RES_CT_EXPOSURE_TIME_ABSOLUTE (1)
#define CTL_DEF_CT_EXPOSURE_TIME_ABSOLUTE (166)
#define CTL_MIN_PU_LOWLIGHTCOMP (0)
#define CTL_MAX_PU_LOWLIGHTCOMP (1)
#define CTL_RES_PU_LOWLIGHTCOMP (1)
#define CTL_DEF_PU_LOWLIGHTCOMP (1)
#define CTL_MIN_PU_WHITE_BALANCE_TEMPERATURE (2800)
#define CTL_MAX_PU_WHITE_BALANCE_TEMPERATURE (6500)
#define CTL_RES_PU_WHITE_BALANCE_TEMPERATURE (10)
#define CTL_DEF_PU_WHITE_BALANCE_TEMPERATURE (4600)
#define CTL_MIN_PU_WHITE_BALANCE_COMPONENT (0x00010001)
#define CTL_MAX_PU_WHITE_BALANCE_COMPONENT (0x00FF00FF)
#define CTL_RES_PU_WHITE_BALANCE_COMPONENT (0X00010001)
#define CTL_DEF_PU_WHITE_BALANCE_COMPONENT (0x00400040)
#define CTL_MIN_PU_WHITE_BALANCE_TEMP_AUTO_CONTROL (0)
#define CTL_MAX_PU_WHITE_BALANCE_TEMP_AUTO_CONTROL (1)
#define CTL_RES_PU_WHITE_BALANCE_TEMP_AUTO_CONTROL (1)
#define CTL_DEF_PU_WHITE_BALANCE_TEMP_AUTO_CONTROL (1)
#define CTL_MIN_PU_BRIGHTNESS (-64)
#define CTL_MAX_PU_BRIGHTNESS (64)
#define CTL_RES_PU_BRIGHTNESS (1)
#define CTL_DEF_PU_BRIGHTNESS (0)
#define CTL_MIN_PU_CONTRAST (0)
#define CTL_MAX_PU_CONTRAST (100)
#define CTL_RES_PU_CONTRAST (1)
#define CTL_DEF_PU_CONTRAST (50)
#define CTL_MIN_PU_HUE (-180)
#define CTL_MAX_PU_HUE (180)
#define CTL_RES_PU_HUE (1)
#define CTL_DEF_PU_HUE (0)
#define CTL_MIN_PU_SATURATION 0
#define CTL_MAX_PU_SATURATION (100)
#define CTL_RES_PU_SATURATION (1)
#define CTL_DEF_PU_SATURATION (64)
#define CTL_MIN_PU_SHARPNESS (0)
#define CTL_MAX_PU_SHARPNESS (100)
#define CTL_RES_PU_SHARPNESS (1)
#define CTL_DEF_PU_SHARPNESS (50)
#define CTL_MIN_PU_GAMMA (100)
#define CTL_MAX_PU_GAMMA (500)
#define CTL_RES_PU_GAMMA (1)
#define CTL_DEF_PU_GAMMA (300)
#define CTL_MIN_PU_BACKLIGHTCOMP (0)
#define CTL_MAX_PU_BACKLIGHTCOMP (2)
#define CTL_RES_PU_BACKLIGHTCOMP (1)
#define CTL_DEF_PU_BACKLIGHTCOMP (0)
#define CTL_MIN_PU_GAIN (0)
#define CTL_MAX_PU_GAIN (128)
#define CTL_RES_PU_GAIN (1)
#define CTL_DEF_PU_GAIN (64)
#define PWR_LINE_FRQ_DIS 0x00
#define PWR_LINE_FRQ_50 0x01
#define PWR_LINE_FRQ_60 0x02
#define CTL_MIN_PU_PWRLINEFRQ (PWR_LINE_FRQ_DIS)
#define CTL_MAX_PU_PWRLINEFRQ (PWR_LINE_FRQ_60)
#define CTL_RES_PU_PWRLINEFRQ (1)
#define CTL_DEF_PU_PWRLINEFRQ (PWR_LINE_FRQ_50)

#define CTL_MIN_PU_PAN (-16)
#define CTL_MAX_PU_PAN (16)
#define CTL_RES_PU_PAN (1)
#define CTL_DEF_PU_PAN (0)

#define CTL_MIN_PU_TILT (-12)
#define CTL_MAX_PU_TILT (12)
#define CTL_RES_PU_TILT (1)
#define CTL_DEF_PU_TILT (0)

#define CTL_MIN_PU_ZOOM (0)
#define CTL_MAX_PU_ZOOM (3)
#define CTL_RES_PU_ZOOM (1)
#define CTL_DEF_PU_ZOOM (0)

#define CTL_MIN_PU_ROLL (0)
#define CTL_MAX_PU_ROLL (3)
#define CTL_RES_PU_ROLL (1)
#define CTL_DEF_PU_ROLL (0)
#define CTL_MIN_CT_FOCUS_ABSOLUTE (0)
#define CTL_MAX_CT_FOCUS_ABSOLUTE (1023)
#define CTL_RES_CT_FOCUS_ABSOLUTE (1)
#define CTL_DEF_CT_FOCUS_ABSOLUTE (68)

#define CTL_MIN_CT_FOCUS_AUTO (0)
#define CTL_MAX_CT_FOCUS_AUTO (1)
#define CTL_RES_CT_FOCUS_AUTO (1)
#define CTL_DEF_CT_FOCUS_AUTO (1)

#define CTL_MIN_EXTU_TRAPEZIUMCORRECTION (-10)
#define CTL_MAX_EXTU_TRAPEZIUMCORRECTION (10)
#define CTL_RES_EXTU_TRAPEZIUMCORRECTION (1)
#define CTL_DEF_EXTU_TRAPEZIUMCORRECTION (0)

#define EXPOSURE_TIME_AUTO_MOD_MANUAL 0X01
#define EXPOSURE_TIME_AUTO_MOD_AUTO 0X02
#define EXPOSURE_TIME_AUTO_MOD_SHUTPRO 0X04
#define EXPOSURE_TIME_AUTO_MOD_APERTPRO 0X08

#define CTL_CHNGFLG_RDY 0x00
#define CTL_CHNGFLG_NOTRDY 0x01
#define CTL_CHNGFLG_ASYN_NEED_NOTIFY 0X02
#define CTL_CHNGFLG_FAILED_NEED_NOTIFY 0X03
#define CTL_CHNGFLG_AUTO_NEED_NOTIFY 0X04
#define CTL_CHNGFLG_INFOCHNG_NEED_NOTIFY 0X05

/*
 A.9.4. Camera Terminal Control Selectors
*/
#define CT_CONTROL_UNDEFINED 0x00
#define CT_SCANNING_MODE_CONTROL 0x01
#define CT_AE_MODE_CONTROL 0x02
#define CT_AE_PRIORITY_CONTROL 0x03
#define CT_EXPOSURE_TIME_ABSOLUTE_CONTROL 0x04
#define CT_EXPOSURE_TIME_RELATIVE_CONTROL 0x05
#define CT_FOCUS_ABSOLUTE_CONTROL 0x06
#define CT_FOCUS_RELATIVE_CONTROL 0x07
#define CT_FOCUS_AUTO_CONTROL 0x08
#define CT_IRIS_ABSOLUTE_CONTROL 0x09
#define CT_IRIS_RELATIVE_CONTROL 0x0A
#define CT_ZOOM_ABSOLUTE_CONTROL 0x0B
#define CT_ZOOM_RELATIVE_CONTROL 0x0C
#define CT_PANTILT_ABSOLUTE_CONTROL 0x0D
#define CT_PANTILT_RELATIVE_CONTROL 0x0E
#define CT_ROLL_ABSOLUTE_CONTROL 0x0F
#define CT_ROLL_RELATIVE_CONTROL 0x10
#define CT_PRIVACY_CONTROL 0x11
#define CT_ROI_CONTROL		0x14
#define CT_CTL_SEL_FOCUS_AUTO		(0x0002)

/*
A.9.5. Processing Unit Control Selectors
*/
#define PU_CONTROL_UNDEFINED 0x00
#define PU_BACKLIGHT_COMPENSATION_CONTROL 0x01
#define PU_BRIGHTNESS_CONTROL 0x02
#define PU_CONTRAST_CONTROL 0x03
#define PU_GAIN_CONTROL 0x04
#define PU_POWER_LINE_FREQUENCY_CONTROL 0x05
#define PU_HUE_CONTROL 0x06
#define PU_SATURATION_CONTROL 0x07
#define PU_SHARPNESS_CONTROL 0x08
#define PU_GAMMA_CONTROL 0x09
#define PU_WHITE_BALANCE_TEMPERATURE_CONTROL 0x0A
#define PU_WHITE_BALANCE_TEMPERATURE_AUTO_CONTROL 0x0B
#define PU_WHITE_BALANCE_COMPONENT_CONTROL 0x0C
#define PU_WHITE_BALANCE_COMPONENT_AUTO_CONTROL 0x0D
#define PU_DIGITAL_MULTIPLIER_CONTROL 0x0E
#define PU_DIGITAL_MULTIPLIER_LIMIT_CONTROL 0x0F
#define PU_HUE_AUTO_CONTROL 0x10
#define PU_ANALOG_VIDEO_STANDARD_CONTROL 0x11
#define PU_ANALOG_LOCK_STATUS_CONTROL 0x12

#define CT_CTL_SEL_SCAN_MODE (0x0001)
#define CT_CTL_SEL_AUTO_EXP_MODE	(0x0002)
#define CT_CTL_SEL_AUTO_EXP_PRY		(0x0004)
#define CT_CTL_SEL_EXPOSURE_TIME_ABS	(0x0008)
#define CT_CTL_SEL_EXPOSURE_TIME_REL	(0x0010)
#define CT_CTL_SEL_FOCUS_ABS		(0x0020)
#define CT_CTL_SEL_FOCUS_REL		(0x0040)
#define CT_CTL_SEL_IRIS_ABS		(0x0080)
#define CT_CTL_SEL_IRIS_REL		(0x0100)
#define CT_CTL_SEL_ZOOM_ABS		(0x0200)
#define CT_CTL_SEL_ZOOM_REL		(0x0400)
#define CT_CTL_SEL_PANTILT_ABS		(0x0800)
#define CT_CTL_SEL_PANTILT_REL		(0x1000)
#define CT_CTL_SEL_ROLL_ABS		(0x2000)
#define CT_CTL_SEL_ROLL_REL		(0x4000)

#define PU_CTL_SEL_BRIGHTNESS (0x0001)
#define PU_CTL_SEL_CONTRAST (0x0002)
#define PU_CTL_SEL_HUE (0x0004)
#define PU_CTL_SEL_SATURATION (0x0008)
#define PU_CTL_SEL_SHARPNESS (0x0010)
#define PU_CTL_SEL_GAMMA (0x0020)
#define PU_CTL_SEL_WHITE_BALANCE_TEMPERATURE (0x0040)
#define PU_CTL_SEL_WHITE_BALANCE_COMPONENT (0x0080)
#define PU_CTL_SEL_BACKLIGHT_COMPENSATION (0x0100)
#define PU_CTL_SEL_GAIN (0x0200)
#define PU_CTL_SEL_POWER_LINE_FREQUENCY (0x0400)
#define PU_CTL_SEL_HUE_AUTO (0x0800)
#define PU_CTL_SEL_WHITE_BALANCE_TEMPERATURE_AUTO (0x1000)
#define PU_CTL_SEL_WHITE_BALANCE_COMPONENT_AUTO (0x2000)
#define PU_CTL_SEL_DIGITAL_MULTIPLIER (0x4000)
#define PU_CTL_SEL_DIGITAL_MULTIPLIER_LIMIT (0x8000)

#define CONTROL_ATTR_SIGNED (1<<7)
#define CONTROL_ATTR_UNSIGNED (0<<7)

#define CONTROL_OP_GET_CUR	(1 << 0)
#define CONTROL_OP_SET_CUR	(1 << 1)
#define CONTROL_OP_GET_MIN	(1 << 2)
#define CONTROL_OP_GET_MAX	(1 << 3)
#define CONTROL_OP_GET_RES		(1 << 4)
#define CONTROL_OP_GET_DEF	(1 << 5)
#define CONTROL_OP_GET_LEN (1 << 6)

#define CONTROL_INFO_SP_GET		 (1 << 0)
#define CONTROL_INFO_SP_SET		 (1 << 1)
#define CONTROL_INFO_DIS_BY_AUTO (1 << 2)
#define CONTROL_INFO_SP_AUTOUPDATA (1 << 3)
#define CONTROL_INFO_SP_ASYNC		 (1 << 4)

#define UVC_EVENT_FIRST		(V4L2_EVENT_PRIVATE_START + 0)
#define UVC_EVENT_CONNECT	(V4L2_EVENT_PRIVATE_START + 0)
#define UVC_EVENT_DISCONNECT	(V4L2_EVENT_PRIVATE_START + 1)
#define UVC_EVENT_STREAMON	(V4L2_EVENT_PRIVATE_START + 2)
#define UVC_EVENT_STREAMOFF	(V4L2_EVENT_PRIVATE_START + 3)
#define UVC_EVENT_SETUP		(V4L2_EVENT_PRIVATE_START + 4)
#define UVC_EVENT_DATA		(V4L2_EVENT_PRIVATE_START + 5)
#define UVC_EVENT_LAST		(V4L2_EVENT_PRIVATE_START + 5)

#define VS_CONTROL_UNDEFINED 0x00
#define VS_PROBE_CONTROL 0x01
#define VS_COMMIT_CONTROL 0x02
#define VS_STILL_PROBE_CONTROL 0x03
#define VS_STILL_COMMIT_CONTROL 0x04
#define VS_STILL_IMAGE_TRIGGER_CONTROL 0x05
#define VS_STREAM_ERROR_CODE_CONTROL 0x06
#define VS_GENERATE_KEY_FRAME_CONTROL 0x07
#define VS_UPDATE_FRAME_SEGMENT_CONTROL 0x08
#define VS_SYNCH_DELAY_CONTROL 0x09

#define CTL_SIZE_VS_PROBE_1V5 0x30
#define CTL_SIZE_VS_PROBE_1V1 0x22
#define CTL_SIZE_VS_PROBE_1V0 0x1a
#define CTL_SIZE_VS_COMMIT_1V5 CTL_SIZE_VS_PROBE_1V5
#define CTL_SIZE_VS_COMMIT_1V1 CTL_SIZE_VS_PROBE_1V1
#define CTL_SIZE_VS_COMMIT_1V0 CTL_SIZE_VS_PROBE_1V0

#define CTL_SIZE_VS_STILL_PROBE 11
#define CTL_SIZE_VS_STILL_COMMIT CTL_SIZE_VS_STILL_PROBE

#define CTL_INFO_VS_PROBE (CONTROL_INFO_SP_GET|CONTROL_INFO_SP_SET)
#define CTL_INFO_VS_COMMIT (CONTROL_INFO_SP_GET|CONTROL_INFO_SP_SET)
#define CTL_INFO_VS_STILL_PROBE (CONTROL_INFO_SP_GET|CONTROL_INFO_SP_SET)
#define CTL_INFO_VS_STILL_COMMIT (CONTROL_INFO_SP_GET|CONTROL_INFO_SP_SET)
#define CTL_INFO_VS_STILL_IMAGE_TRIGGER \
	(CONTROL_INFO_SP_GET|CONTROL_INFO_SP_SET)
#define CTL_INFO_VS_ERROR_CODE (CONTROL_INFO_SP_GET)

#define CONTROL_LEN_1 (1)
#define CONTROL_LEN_2 (2)
#define CONTROL_LEN_4 (4)
#define CONTROL_LEN_8 (8)

#define	REQUEST_TYPE		0x60
#define	STANDARD_REQUEST	0x00
#define	CLASS_REQUEST		0x20
#define	VENDOR_REQUEST		0x40

#define IF_IDX_VIDEOCONTROL 0x00
#define IF_IDX_VIDEOSTREAMING 0X01

#define VS_ERR_NOERROR (0)
#define VS_ERR_CNTPROTECT (1)
#define VS_ERR_IBUFUNDERRUN (2)
#define VS_ERR_DATDISCONT (3)
#define VS_ERR_OBUFUNDERRUN (4)
#define VS_ERR_OBUFOVERRUN (5)
#define VS_ERR_FMTCHANGE (6)
#define VS_ERR_STLIMGCAPERR (7)
#define VS_ERR_UNKNOWN (8)

#define DEV_CLOCK_FRQ 12000000

#define VC_CONTROL_UNDEFINED 0x00
#define VC_VIDEO_POWER_MODE_CONTROL 0x01
#define VC_REQUEST_ERROR_CODE_CONTROL 0x02

#define VC_ERR_NOERROR 0x00
#define VC_ERR_NOTRDY 0x01
#define VC_ERR_WRNGSTAT 0x02
#define VC_ERR_PWR 0x03
#define VC_ERR_OUTOFRANGE 0x04
#define VC_ERR_INVDUNIT 0x05
#define VC_ERR_INVDCTL 0x06
#define VC_ERR_INVDREQ 0x07
#define VC_ERR_UNKNOWN 0xFF

#define ENT_ID_CAMERA_IT		0x01
#define ENT_ID_PROCESSING_UNIT	0x02
#define ENT_ID_EXTENSION_UNIT_DBG	0x04
#define ENT_ID_OUTPUT_TRM		0x03
#define ENT_ID_RTK_EXTENDED_CTL_UNIT	0x06
#define ENT_ID_H264_ENCODING_UNIT	0x05

#define STS_PKT_ATTR_VALUE_CHANGE (0x00)
#define STS_PKT_ATTR_INFO_CHANGE (0x01)
#define STS_PKT_ATTR_FAILED_CHANGE (0x02)

#define RC_UNDEFINED 0x00
#define SET_CUR 0x01
#define GET_CUR 0x81
#define GET_MIN 0x82
#define GET_MAX 0x83
#define GET_RES 0x84
#define GET_LEN 0x85
#define GET_INFO 0x86
#define GET_DEF 0x87

#define UVCIOC_SEND_RESPONSE		_IOW('U', 1, struct uvc_request_data)
#define UVCIOC_SEND_RESPONSE_INT	_IOW('U', 7, struct uvc_request_data)

#define BUFFER_COUNT 4

#define ANDROIDUVC_IOC_MAGIC		0x74
#define ANDROIDUVC_SETFORMAT		1
#define ANDROIDUVC_CLEARFORMAT	2
#define ANDROIDUVC_QUERYFORMAT	3
#define ANDROIDUVC_WAIT_NAK	4
#define ANDROIDUVC_GET_NUM	5
#define ANDROIDUVC_EN_NAK	6
#define ANDROIDUVC_PRODUCE_DESC 7

#define ANDROIDUVC_IOC_SETFORMAT	_IOW(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_SETFORMAT, struct format_setting)
#define ANDROIDUVC_IOC_QUERYFORMAT	_IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_QUERYFORMAT, struct format_setting)
#define ANDROIDUVC_IOC_CLRFORMAT	_IO(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_CLEARFORMAT)
#define ANDROIDUVC_IOC_WAIT_NAK	_IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_WAIT_NAK, int)
#define ANDROIDUVC_IOC_GET_NUM	_IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_GET_NUM, int)
#define ANDROIDUVC_IOC_EN_NAK	_IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_EN_NAK, int)
#define ANDROIDUVC_IOC_EN_NAK	_IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_EN_NAK, int)
#define ANDROIDUVC_IOC_CLEAR_NUM _IOWR(ANDROIDUVC_IOC_MAGIC, ANDROIDUVC_CLEAR_NUM, int)
#define ANDROIDUVC_IOC_PRODUCE_DESC _IOWR(ANDROIDUVC_IOC_MAGIC, \
	ANDROIDUVC_PRODUCE_DESC, int)
#define USB_VDREQUEST_GET_STATUS 0x6
#define USB_VDREQUEST_DEV_STS_R 0x7

#ifdef DEBUG
#define DPRINT(x...) \
	printf(x)
#else
#define DPRINT(x...)
#endif /*DEBUG*/
#define _RT_VID_L_       0xda
#define _RT_VID_H_      0x0b
#define _PID_L_   0x01
#define _PID_H_   0x39
#define	_FW_MAIN_VER_	0x41
#define	_FW_SUB_VER_	0x22
#define AP_MAIN_VERSION		0x10
#define AP_SUB_VERSION		0x01
#define _FWDL_PID_H_      0x58
#define _FWDL_PID_L_      0xFF

#define FPS_120	(0x0001<<0)
#define FPS_60	(0x0001<<1)
#define FPS_30	(0x0001<<2)
#define FPS_25	(0x0001<<3)
#define FPS_24	(0x0001<<4)
#define FPS_23	(0x0001<<5)
#define FPS_20	(0x0001<<6)
#define FPS_15	(0x0001<<7)
#define FPS_12	(0x0001<<8)
#define FPS_11	(0x0001<<9)
#define FPS_10	(0x0001<<10)
#define FPS_9	(0x0001<<11)
#define FPS_8	(0x0001<<12)
#define FPS_7	(0x0001<<13)
#define FPS_5	(0x0001<<14)
#define FPS_3	(0x0001<<15)

struct ctlitemu8_t {
	unsigned char min;
	unsigned char max;
	unsigned char res;
	unsigned char def;
	unsigned char des;
	unsigned char last;
};

struct ctlitems8_t {
	char min;
	char max;
	unsigned char res;
	char def;
	char des;
	char last;
};

struct ctlitemu16_t {
	unsigned short min;
	unsigned short max;
	unsigned short res;
	unsigned short def;
	unsigned short des;
	unsigned short last;
};

struct ctlitems16_t {
	short min;
	short max;
	unsigned short res;
	short def;
	short des;
	short last;
};

struct ctlitemu32_t {
	unsigned int min;
	unsigned int max;
	unsigned int res;
	unsigned int def;
	unsigned int des;
	unsigned int last;
};

struct ctlitems32_t {
	int min;
	int max;
	unsigned int res;
	int def;
	int des;
	int last;
};

union ctlattr_t {
	struct ctlitemu8_t ctlitemu8;
	struct ctlitems8_t ctlitems8;
	struct ctlitemu16_t ctlitemu16;
	struct ctlitems16_t ctlitems16;
	struct ctlitemu32_t ctlitemu32;
	struct ctlitems32_t ctlitems32;
};

struct ctl_t {
	unsigned char info;
	unsigned char changeflag;
	unsigned char opmask;
	unsigned char len;
	union ctlattr_t *pattr;
};

struct vsprobcommstruct {
	unsigned short bmhint;
	unsigned char bformatindex;
	unsigned char bframeindex;
	unsigned int dwframeinterval;
	unsigned int dwmaxvideoframesize;
	unsigned int dwmaxpayloadtransfersize;
};

struct buffer {
	void *start;
	size_t length;
};

struct uvc_request_data {
	__s32 length;
	__u8 dir;
	__u8 stall;
	__u8 data[60];
};

struct usb_ctrlrequest {
	__u8 brequesttype;
	__u8 brequest;
	__le16 wvalue;
	__le16 windex;
	__le16 wlength;
} __packed;

struct format_setting {
	unsigned int type;
	unsigned short width;
	unsigned short height;
	unsigned int fps;
	unsigned int fileindex;
};

#endif
