#!/usr/bin/perl
#
# Realtek Semiconductor Corp.
#
# Tony Wu (tonywu@realtek.com)
# Dec. 07, 2008
#
# The Right Thing
#

my @CONFIG = ();
my %KEYHASH = (); 
my $config = '';
my $header = '';
my $key, $val;


if (@ARGV != 1) {
  print "usage: hconf DIR_ROOT", "\n";
  exit -1;
}

$DIR_ROOT = $ARGV[0];

print "INFO: generating config.h from $DIR_ROOT", "\n";

push @CONFIG, $DIR_ROOT . '/linux-2.6.23/.config';
push @CONFIG, $DIR_ROOT . '/users/.config';
push @CONFIG, $DIR_ROOT . '/users/busybox/.config';
$header = $DIR_ROOT . '/tmpfs/include/config.h';

open(DOTH, '>', $header) || die $_;

foreach $config (@CONFIG) {
  open(PIPE, $config) || die $_;
  while (<PIPE>) {
    chomp;
    if (m|^([^=]+)=(.*)|) {
      $key = $1;
      $val = $2;

      if ($HASH{$key} == 1) {
        print "ERROR: duplicate key $key", "\n";
      }
      $HASH{$key} = 1;

      $val = 1 if (length($val)==1 and $val =~ m|[yY]|);
      print DOTH "#define $key $val", "\n";
    }
  }
  close(PIPE);
}

close(DOTH);

exit 0;
