#!/bin/sh

mknod /dev/console c 5 1
mknod /dev/dbg_iomem c 120 0
mknod /dev/usb_phy_mdio c 121 0
mknod /dev/efuse c 122 0
mknod /dev/hconf c 123 0
mknod /dev/ram0 b 1 0
mknod /dev/android_uvc c 243 0
