#ifndef _RLX_CRYPTO_H_
#define _RLX_CRYPTO_H_

#define RLX_REG_KEY_DATA0		0x00
#define RLX_REG_KEY_DATA1		0x04
#define RLX_REG_KEY_DATA2		0x08
#define RLX_REG_KEY_DATA3		0x0C
#define RLX_REG_KEY_DATA4		0x10
#define RLX_REG_KEY_DATA5		0x14
#ifdef CONFIG_HW_VER_RTS3901
#define RLX_REG_KEY_DATA6		0x18
#define RLX_REG_KEY_DATA7		0x1C
#endif
#define RLX_REG_IV_IN_DATA0		0x20
#define RLX_REG_IV_IN_DATA1		0x24
#define RLX_REG_IV_IN_DATA2		0x28
#define RLX_REG_IV_IN_DATA3		0x2C
#define RLX_REG_IV_OUT_DATA0		0x30
#define RLX_REG_IV_OUT_DATA1		0x34
#define RLX_REG_IV_OUT_DATA2		0x38
#define RLX_REG_IV_OUT_DATA3		0x3C
#define RLX_REG_IN_TABLE_ADDR		0x40
#define RLX_REG_IN_BUF_NUM		0x44
#define RLX_REG_OUT_TABLE_ADDR		0x48
#define RLX_REG_OUT_BUF_NUM		0x4C
#define RLX_REG_CIPHER_CTL		0x50
#define RLX_REG_CIPHER_INT_EN		0x54
#define RLX_REG_CIPHER_INT_FLAG		0x58
#define RLX_REG_CIPHER_STS		0x5C
#define RLX_REG_FINISH_BLOCK_NUM	0x60
#define RLX_REG_DATA_IN_LENGTH		0x64

/* RLX_REG_CIPHER_CTL */
#ifdef CONFIG_HW_VER_RTS3901
#define RLX_AES_MODE_SEL		10
#endif
#define RLX_ALGORITHM_SEL		8
#define RLX_OPERATION_MODE		5
#define RLX_PADDING_SEL			4
#define RLX_ENCTYPT_DECTYPT_SEL		3
#define RLX_BUSY_FLAG			2
#define RLX_STOP_CIPHER			1
#define RLX_START_CIPHER		0

#define AES_BLOCK_SIZE			16
#define DES_BLOCK_SIZE			8

#endif
